### ISSUE TITLE
Docker Xhost+local: 

### ISSUE THREAD

**Issue by amydenisse8** [geaxgx/tello-humanpose-openvino#3]
Hello, I am currently stuck with authorizing my docker host with the X server. I have never used Docker before so I am kind lost on what I need to do. I ran the docker container and in the terminal I inputted "xhost +local:" but in return it says "xhost: command not found." I would appreciate any help. Thank you!

**Comment by geaxgx** [comment]
From your description, it seems that you run the  "xhost +local:" into the shell you get after running the docker container. But actually, you have to run it before.

**Comment by amydenisse8** [comment]
Turns out that was the problem. Thank you so much!
